export type Locale = 'en' | 'zh';

export type TranslationTree = {
  nav: {
    configTool: string;
    github: string;
    langEn: string;
    langZh: string;
  };
  hero: {
    titleLine1: string;
    titleLine2: string;
    subtitle: string;
    openConfig: string;
    viewGithub: string;
  };
  features: {
    sectionTitle: string;
    items: { title: string; desc: string }[];
  };
  quickStart: {
    sectionTitle: string;
    steps: { title: string; desc: string }[];
    openConfig: string;
    footnote: string;
    footnoteLink: string;
    footnoteEnd: string;
    readmeQuickStartUrl: string;
  };
  sampleReport: {
    sectionTitle: string;
    subtitleBeforeLink: string;
    subtitleAfterLink: string;
    reportTitle: string;
    /** Full header chips, localized (no hard-coded Chinese in EN) */
    metaResearcher: string;
    metaPapers: string;
    metaCitations: string;
    targetTitle: string;
    targetMeta: string;
    table: {
      num: string;
      citingPaper: string;
      institution: string;
      venue: string;
      year: string;
      rank: string;
      context: string;
      sentiment: string;
      analysis: string;
    };
    highPraiseCard: string;
    notableAuthors: string;
    topInstitutions: string;
    summary: {
      high: string;
      neutral: string;
      critical: string;
      footnote: string;
    };
    sentiment: {
      high: string;
      neutral: string;
      critical: string;
    };
    linkPacketGame: string;
    readmeQuickStartUrl: string;
    viewFull: string;
  };
  footer: {
    line: string;
  };
  config: {
    title: string;
    onlineBannerBefore: string;
    onlineBannerLink: string;
    onlineBannerAfter: string;
    readmeQuickStartUrl: string;
    workingDir: string;
    notSelected: string;
    chooseFolder: string;
    change: string;
    fsUnsupported: string;
    steps: string[];
  };
};

export const translations: Record<Locale, TranslationTree> = {
  en: {
    nav: {
      configTool: 'Config Tool',
      github: 'GitHub',
      langEn: 'EN',
      langZh: 'ZH',
    },
    hero: {
      titleLine1: "Analyze Your Paper's",
      titleLine2: 'Citation Impact',
      subtitle:
        'An AI-powered agent skill that automatically retrieves, filters, and analyzes how your academic papers are cited — complete with CCF rankings and sentiment analysis.',
      openConfig: 'Open Config Tool',
      viewGithub: 'View on GitHub',
    },
    features: {
      sectionTitle: 'Key Features',
      items: [
        {
          title: 'Smart Scholar Search',
          desc: 'Find researchers via Google Scholar ID or name using the OpenAlex academic graph.',
        },
        {
          title: 'Flexible Filtering',
          desc: 'Filter citing papers by CCF ranking (A/B/C), publication year, author, and affiliation.',
        },
        {
          title: 'PDF Analysis',
          desc: 'Automatically downloads open-access PDFs and extracts the exact citation context.',
        },
        {
          title: 'AI Sentiment',
          desc: 'The agent analyzes whether each citation is high praise, neutral reference, or critique.',
        },
        {
          title: 'Parallel Processing',
          desc: 'Processes multiple papers concurrently for maximum speed.',
        },
        {
          title: 'Multi-Platform',
          desc: 'Works as both a Cursor Agent Skill and a Claude Code Agent Skill.',
        },
      ],
    },
    quickStart: {
      sectionTitle: 'Quick Start',
      steps: [
        {
          title: 'Configure',
          desc: 'Use the Config Tool to search your papers, select citing papers, and set filter conditions.',
        },
        {
          title: 'Export',
          desc: 'Choose a local working directory. Config and PDF folders are saved directly to your machine.',
        },
        {
          title: 'Run the Agent',
          desc: 'Open the workspace in Cursor or Claude Code and let the agent analyze your citations.',
        },
      ],
      openConfig: 'Open Config Tool',
      footnote: 'Requires Chrome or Edge. For best performance,',
      footnoteLink: 'run locally',
      footnoteEnd: '.',
      readmeQuickStartUrl: 'https://github.com/yuanmu97/citation-impact#quick-start',
    },
    sampleReport: {
      sectionTitle: 'Example Output',
      subtitleBeforeLink: 'Real report generated by analyzing',
      subtitleAfterLink:
        '. The agent extracts citation contexts, classifies each citation, and annotates high-praise ones with notable scholar & institution backgrounds.',
      reportTitle: 'Citation impact report',
      metaResearcher: 'Researcher: Mu Yuan',
      metaPapers: 'Papers analyzed: 1',
      metaCitations: 'Matching citations: 5',
      targetTitle: 'PacketGame: Multi-stream packet gating for concurrent video inference at scale',
      targetMeta: 'ACM SIGCOMM 2023 · DOI: 10.1145/3603269.3604825',
      table: {
        num: '#',
        citingPaper: 'Citing paper',
        institution: 'Institution',
        venue: 'Venue',
        year: 'Year',
        rank: 'Rank',
        context: 'Citation context',
        sentiment: 'Sentiment',
        analysis: 'Notes',
      },
      highPraiseCard: 'High-praise deep annotation',
      notableAuthors: 'Notable authors',
      topInstitutions: 'Top institutions',
      summary: {
        high: 'High praise:',
        neutral: 'Neutral:',
        critical: 'Critical:',
        footnote:
          'This high-praise citation involves 3 notable scholars (IEEE Fellows, national talent titles, etc.) and 2 top institutions (NJU State Key Lab, Tsinghua AIR), reinforcing recognition in the field.',
      },
      sentiment: {
        high: 'High praise',
        neutral: 'Neutral',
        critical: 'Critical',
      },
      linkPacketGame: 'PacketGame (SIGCOMM 2023)',
      readmeQuickStartUrl: 'https://github.com/yuanmu97/citation-impact#quick-start',
      viewFull: 'View full report on GitHub →',
    },
    footer: {
      line: 'Citation Impact Analyzer — MIT License —',
    },
    config: {
      title: 'Configuration Tool',
      onlineBannerBefore: 'You are using the online hosted version. For better performance and reliability, we recommend',
      onlineBannerLink: 'running locally',
      onlineBannerAfter: '.',
      readmeQuickStartUrl: 'https://github.com/yuanmu97/citation-impact#quick-start',
      workingDir: 'Working Directory:',
      notSelected: 'Not selected',
      chooseFolder: 'Choose Folder',
      change: 'Change',
      fsUnsupported: 'File System Access not supported — use Chrome or Edge',
      steps: ['Search Author', 'Select Papers', 'Citing Papers', 'PDF Prep', 'Export'],
    },
  },
  zh: {
    nav: {
      configTool: '配置工具',
      github: 'GitHub',
      langEn: 'EN',
      langZh: '中文',
    },
    hero: {
      titleLine1: '分析论文的',
      titleLine2: '被引影响力',
      subtitle:
        '基于 AI Agent 的技能：自动检索、筛选并分析他人如何引用你的论文——含 CCF 分级与引用情感（高度评价 / 一般引用 / 批评性引用）分析。',
      openConfig: '打开配置工具',
      viewGithub: '在 GitHub 上查看',
    },
    features: {
      sectionTitle: '核心特性',
      items: [
        {
          title: '智能学者检索',
          desc: '通过 Google Scholar ID 或姓名，结合 OpenAlex 学术图谱定位研究者。',
        },
        {
          title: '灵活筛选',
          desc: '按 CCF 分级（A/B/C）、发表年份、作者、机构等他引条件筛选。',
        },
        {
          title: 'PDF 分析',
          desc: '自动下载开放获取 PDF，并抽取引用处的原文语境。',
        },
        {
          title: 'AI 情感分析',
          desc: 'Agent 判断每条引用属于高度评价、一般引用还是批评性提及。',
        },
        {
          title: '并行处理',
          desc: '多篇论文并发处理，加快整体流程。',
        },
        {
          title: '多平台',
          desc: '同时支持 Cursor Agent Skill 与 Claude Code Agent Skill。',
        },
      ],
    },
    quickStart: {
      sectionTitle: '快速开始',
      steps: [
        {
          title: '配置',
          desc: '在配置工具中检索论文、选择他引论文并设置筛选条件。',
        },
        {
          title: '导出',
          desc: '选择本地工作目录，配置与 PDF 文件夹直接保存在本机。',
        },
        {
          title: '运行 Agent',
          desc: '在 Cursor 或 Claude Code 中打开工作区，让 Agent 完成被引分析。',
        },
      ],
      openConfig: '打开配置工具',
      footnote: '需使用 Chrome 或 Edge。为获得最佳性能，建议',
      footnoteLink: '在本地运行',
      footnoteEnd: '。',
      readmeQuickStartUrl:
        'https://github.com/yuanmu97/citation-impact/blob/main/README.zh-CN.md#快速开始',
    },
    sampleReport: {
      sectionTitle: '示例输出',
      subtitleBeforeLink: '以下示例基于对',
      subtitleAfterLink:
        ' 的分析生成。Agent 会抽取引用原文、分类评价类型，并对「高度评价」补充知名学者与头部机构等背景信息。',
      reportTitle: '学术论文被引情况报告',
      metaResearcher: '研究者: Mu Yuan (袁牧)',
      metaPapers: '分析论文: 1 篇',
      metaCitations: '符合条件被引: 5 次',
      targetTitle: 'PacketGame: Multi-stream packet gating for concurrent video inference at scale',
      targetMeta: 'ACM SIGCOMM 2023 · DOI: 10.1145/3603269.3604825',
      table: {
        num: '#',
        citingPaper: '他引论文',
        institution: '机构',
        venue: '发表出处',
        year: '年份',
        rank: '评级',
        context: '引用原文',
        sentiment: '评价类型',
        analysis: '分析说明',
      },
      highPraiseCard: '高度评价深度标注',
      notableAuthors: '知名作者',
      topInstitutions: '头部机构',
      summary: {
        high: '高度评价:',
        neutral: '一般引用:',
        critical: '批评性引用:',
        footnote:
          '该条高度评价涉及 3 位知名学者（IEEE Fellow、国家人才称号等）与 2 所头部机构（南京大学国家重点实验室、清华大学 AIR），进一步体现领域认可度。',
      },
      sentiment: {
        high: '高度评价',
        neutral: '一般引用',
        critical: '批评性引用',
      },
      linkPacketGame: 'PacketGame（SIGCOMM 2023）',
      readmeQuickStartUrl:
        'https://github.com/yuanmu97/citation-impact/blob/main/README.zh-CN.md#快速开始',
      viewFull: '在 GitHub 查看完整报告 →',
    },
    footer: {
      line: 'Citation Impact Analyzer — MIT 协议 —',
    },
    config: {
      title: '配置工具',
      onlineBannerBefore: '你正在使用在线托管版本。为获得更好性能与稳定性，建议',
      onlineBannerLink: '在本地运行',
      onlineBannerAfter: '。',
      readmeQuickStartUrl:
        'https://github.com/yuanmu97/citation-impact/blob/main/README.zh-CN.md#快速开始',
      workingDir: '工作目录：',
      notSelected: '未选择',
      chooseFolder: '选择文件夹',
      change: '更换',
      fsUnsupported: '当前浏览器不支持文件系统访问 — 请使用 Chrome 或 Edge',
      steps: ['搜索作者', '选择论文', '他引论文', 'PDF 准备', '导出'],
    },
  },
};
