const citations = [
  {
    num: 1,
    title: 'Déjà Vu: Efficient Video-Language Query Engine with Learning-Based Inter-Frame Computation Reuse',
    authors: 'Jinwoo Hwang et al. (11)',
    institution: 'Korea University',
    venue: 'VLDB',
    year: 2025,
    rank: 'B',
    context: '"PacketGame [115] cited as related work in video inference computation reuse."',
    sentiment: '一般引用' as const,
    reasoning: '视频推理领域相关工作引用，属标准背景引用。',
  },
  {
    num: 2,
    title: 'Empower Vision Applications with LoRA LMM',
    authors: 'Liang Mi et al. (13)',
    institution: 'Nanjing Univ.; Tsinghua',
    venue: 'EuroSys',
    year: 2025,
    rank: 'A',
    context: '"Real-time video analytics application [92, 93] needs low latency..." / "...image classification [92], vehicle counting [57]..." / "...like prior work [79, 92]."',
    sentiment: '高度评价' as const,
    reasoning: '3 个章节中 3 次引用，作为实时视频分析领域的代表性工作。',
  },
  {
    num: 3,
    title: 'Palantir: Towards Efficient Super Resolution for Ultra-high-definition Live Streaming',
    authors: 'Xinqi Jin et al. (9)',
    institution: 'Tsinghua; Simon Fraser',
    venue: 'MMSys',
    year: 2025,
    rank: 'A',
    context: '"Commodity cameras...are typically not programmable [49] and thus not suitable for...DAG construction."',
    sentiment: '一般引用' as const,
    reasoning: '§6.1 中作为背景事实引用，无褒贬。',
  },
  {
    num: 4,
    title: 'AMRE: Adaptive Multilevel Redundancy Elimination for Multimodal Mobile Inference',
    authors: 'Qixuan Cai et al. (8)',
    institution: 'Tianjin University',
    venue: 'IEEE TMC',
    year: 2025,
    rank: 'A',
    context: '"Some works reduce model computation by minimizing certain input regions [29], [30], [31]."',
    sentiment: '一般引用' as const,
    reasoning: 'Related Work 中以列举方式归类为输入区域优化工作。',
  },
  {
    num: 5,
    title: 'Online Container Caching with Late-Warm for IoT Data Processing',
    authors: 'Guopeng Li et al. (7)',
    institution: 'USTC; MSRA',
    venue: 'ICDE',
    year: 2024,
    rank: 'A',
    context: '"...experiences a surge in frequency when more objects are detected [16], [17]."',
    sentiment: '一般引用' as const,
    reasoning: 'Introduction 中作为 IoT 推理任务的示例引用。',
  },
];

const sentimentStyle = {
  '高度评价': 'bg-green-50 text-green-700 ring-green-200',
  '一般引用': 'bg-blue-50 text-blue-700 ring-blue-200',
  '批评性引用': 'bg-red-50 text-red-700 ring-red-200',
} as const;

const rankStyle: Record<string, string> = {
  A: 'bg-red-50 text-red-600 ring-red-200',
  B: 'bg-amber-50 text-amber-600 ring-amber-200',
  C: 'bg-gray-50 text-gray-600 ring-gray-200',
};

export default function SampleReport() {
  return (
    <section className="py-20">
      <div className="max-w-6xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-3">Example Output</h2>
        <p className="text-center text-gray-500 mb-10 max-w-2xl mx-auto">
          Real report generated by analyzing{' '}
          <a
            href="https://doi.org/10.1145/3603269.3604825"
            target="_blank"
            rel="noreferrer"
            className="text-primary-600 underline hover:text-primary-700"
          >
            PacketGame (SIGCOMM 2023)
          </a>
          . The agent extracts citation contexts from PDFs, identifies institutions, and classifies each citation automatically.
        </p>

        <div className="rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          {/* Report header */}
          <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
            <div className="flex flex-wrap items-baseline gap-x-6 gap-y-1">
              <h3 className="font-bold text-lg text-gray-900">学术论文被引情况报告</h3>
              <span className="text-sm text-gray-500">研究者: Mu Yuan (袁牧)</span>
              <span className="text-sm text-gray-500">分析论文: 1 篇</span>
              <span className="text-sm text-gray-500">符合条件被引: 5 次</span>
            </div>
          </div>

          {/* Target paper */}
          <div className="px-6 py-4 border-b border-gray-100 bg-white">
            <p className="font-semibold text-gray-800">
              PacketGame: Multi-stream packet gating for concurrent video inference at scale
            </p>
            <p className="text-sm text-gray-500 mt-1">
              ACM SIGCOMM 2023 &nbsp;·&nbsp; DOI: 10.1145/3603269.3604825
            </p>
          </div>

          {/* Citation table */}
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-left text-gray-600">
                  <th className="px-4 py-3 font-semibold w-8">#</th>
                  <th className="px-4 py-3 font-semibold">他引论文</th>
                  <th className="px-4 py-3 font-semibold">机构</th>
                  <th className="px-4 py-3 font-semibold">发表出处</th>
                  <th className="px-4 py-3 font-semibold w-12">年份</th>
                  <th className="px-4 py-3 font-semibold w-12">评级</th>
                  <th className="px-4 py-3 font-semibold min-w-[220px]">引用原文</th>
                  <th className="px-4 py-3 font-semibold w-20">评价类型</th>
                  <th className="px-4 py-3 font-semibold min-w-[180px]">分析说明</th>
                </tr>
              </thead>
              <tbody>
                {citations.map((c) => (
                  <tr key={c.num} className="border-t border-gray-100 align-top">
                    <td className="px-4 py-3 text-gray-400">{c.num}</td>
                    <td className="px-4 py-3 font-medium text-gray-800">
                      {c.title.length > 60 ? c.title.slice(0, 60) + '...' : c.title}
                      <br />
                      <span className="text-xs text-gray-400">{c.authors}</span>
                    </td>
                    <td className="px-4 py-3 text-gray-600">{c.institution}</td>
                    <td className="px-4 py-3 text-gray-600">{c.venue}</td>
                    <td className="px-4 py-3 text-gray-600">{c.year}</td>
                    <td className="px-4 py-3">
                      <span className={`inline-block px-2 py-0.5 text-xs font-bold rounded ring-1 ${rankStyle[c.rank] || ''}`}>
                        {c.rank}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-600 leading-relaxed">
                      <span className="italic text-xs">{c.context}</span>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-block px-2 py-0.5 text-xs font-semibold rounded ring-1 ${sentimentStyle[c.sentiment]}`}>
                        {c.sentiment}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-500 text-xs leading-relaxed">{c.reasoning}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Summary bar */}
          <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex flex-wrap gap-6 text-sm">
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-green-400" />
              <span className="text-gray-600">高度评价: 1 (20%)</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-blue-400" />
              <span className="text-gray-600">一般引用: 4 (80%)</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-orange-400" />
              <span className="text-gray-600">批评性引用: 0</span>
            </div>
          </div>
        </div>

        <p className="text-center mt-6 text-sm text-gray-400">
          <a
            href="https://github.com/yuanmu97/citation-impact/blob/main/example/citation_report.md"
            target="_blank"
            rel="noreferrer"
            className="underline hover:text-gray-600"
          >
            View full report on GitHub &rarr;
          </a>
        </p>
      </div>
    </section>
  );
}
